/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables;


import com.example.demo.Keys;
import com.example.demo.Li;
import com.example.demo.tables.records.TUserDevRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserDev extends TableImpl<TUserDevRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>li.t_user_dev</code>
     */
    public static final TUserDev T_USER_DEV = new TUserDev();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserDevRecord> getRecordType() {
        return TUserDevRecord.class;
    }

    /**
     * The column <code>li.t_user_dev.id</code>.
     */
    public final TableField<TUserDevRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>li.t_user_dev.user_id</code>.
     */
    public final TableField<TUserDevRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>li.t_user_dev.dev_id</code>.
     */
    public final TableField<TUserDevRecord, Integer> DEV_ID = createField(DSL.name("dev_id"), SQLDataType.INTEGER, this, "");

    private TUserDev(Name alias, Table<TUserDevRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserDev(Name alias, Table<TUserDevRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>li.t_user_dev</code> table reference
     */
    public TUserDev(String alias) {
        this(DSL.name(alias), T_USER_DEV);
    }

    /**
     * Create an aliased <code>li.t_user_dev</code> table reference
     */
    public TUserDev(Name alias) {
        this(alias, T_USER_DEV);
    }

    /**
     * Create a <code>li.t_user_dev</code> table reference
     */
    public TUserDev() {
        this(DSL.name("t_user_dev"), null);
    }

    public <O extends Record> TUserDev(Table<O> child, ForeignKey<O, TUserDevRecord> key) {
        super(child, key, T_USER_DEV);
    }

    @Override
    public Schema getSchema() {
        return Li.LI;
    }

    @Override
    public Identity<TUserDevRecord, Integer> getIdentity() {
        return (Identity<TUserDevRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TUserDevRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_DEV_PRIMARY;
    }

    @Override
    public List<UniqueKey<TUserDevRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserDevRecord>>asList(Keys.KEY_T_USER_DEV_PRIMARY);
    }

    @Override
    public TUserDev as(String alias) {
        return new TUserDev(DSL.name(alias), this);
    }

    @Override
    public TUserDev as(Name alias) {
        return new TUserDev(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserDev rename(String name) {
        return new TUserDev(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserDev rename(Name name) {
        return new TUserDev(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
