/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDepUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer depId;
    private Integer userId;

    public TDepUser() {}

    public TDepUser(TDepUser value) {
        this.id = value.id;
        this.depId = value.depId;
        this.userId = value.userId;
    }

    public TDepUser(
        Integer id,
        Integer depId,
        Integer userId
    ) {
        this.id = id;
        this.depId = depId;
        this.userId = userId;
    }

    /**
     * Getter for <code>li.t_dep_user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>li.t_dep_user.id</code>.
     */
    public TDepUser setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>li.t_dep_user.dep_id</code>.
     */
    public Integer getDepId() {
        return this.depId;
    }

    /**
     * Setter for <code>li.t_dep_user.dep_id</code>.
     */
    public TDepUser setDepId(Integer depId) {
        this.depId = depId;
        return this;
    }

    /**
     * Getter for <code>li.t_dep_user.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>li.t_dep_user.user_id</code>.
     */
    public TDepUser setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDepUser (");

        sb.append(id);
        sb.append(", ").append(depId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
