/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDevice implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer devId;
    private String  devName;

    public TDevice() {}

    public TDevice(TDevice value) {
        this.devId = value.devId;
        this.devName = value.devName;
    }

    public TDevice(
        Integer devId,
        String  devName
    ) {
        this.devId = devId;
        this.devName = devName;
    }

    /**
     * Getter for <code>li.t_device.dev_id</code>.
     */
    public Integer getDevId() {
        return this.devId;
    }

    /**
     * Setter for <code>li.t_device.dev_id</code>.
     */
    public TDevice setDevId(Integer devId) {
        this.devId = devId;
        return this;
    }

    /**
     * Getter for <code>li.t_device.dev_name</code>.
     */
    public String getDevName() {
        return this.devName;
    }

    /**
     * Setter for <code>li.t_device.dev_name</code>.
     */
    public TDevice setDevName(String devName) {
        this.devName = devName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDevice (");

        sb.append(devId);
        sb.append(", ").append(devName);

        sb.append(")");
        return sb.toString();
    }
}
