/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMeeting implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        meetName;
    private String        meetDue;
    private String        meetroomName;
    private String        meetDev;
    private LocalDateTime meetStart;
    private LocalDateTime meetEnd;

    public TMeeting() {}

    public TMeeting(TMeeting value) {
        this.id = value.id;
        this.meetName = value.meetName;
        this.meetDue = value.meetDue;
        this.meetroomName = value.meetroomName;
        this.meetDev = value.meetDev;
        this.meetStart = value.meetStart;
        this.meetEnd = value.meetEnd;
    }

    public TMeeting(
        Integer       id,
        String        meetName,
        String        meetDue,
        String        meetroomName,
        String        meetDev,
        LocalDateTime meetStart,
        LocalDateTime meetEnd
    ) {
        this.id = id;
        this.meetName = meetName;
        this.meetDue = meetDue;
        this.meetroomName = meetroomName;
        this.meetDev = meetDev;
        this.meetStart = meetStart;
        this.meetEnd = meetEnd;
    }

    /**
     * Getter for <code>li.t_meeting.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>li.t_meeting.id</code>.
     */
    public TMeeting setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>li.t_meeting.meet_name</code>.
     */
    public String getMeetName() {
        return this.meetName;
    }

    /**
     * Setter for <code>li.t_meeting.meet_name</code>.
     */
    public TMeeting setMeetName(String meetName) {
        this.meetName = meetName;
        return this;
    }

    /**
     * Getter for <code>li.t_meeting.meet_due</code>.
     */
    public String getMeetDue() {
        return this.meetDue;
    }

    /**
     * Setter for <code>li.t_meeting.meet_due</code>.
     */
    public TMeeting setMeetDue(String meetDue) {
        this.meetDue = meetDue;
        return this;
    }

    /**
     * Getter for <code>li.t_meeting.meetroom_name</code>.
     */
    public String getMeetroomName() {
        return this.meetroomName;
    }

    /**
     * Setter for <code>li.t_meeting.meetroom_name</code>.
     */
    public TMeeting setMeetroomName(String meetroomName) {
        this.meetroomName = meetroomName;
        return this;
    }

    /**
     * Getter for <code>li.t_meeting.meet_dev</code>.
     */
    public String getMeetDev() {
        return this.meetDev;
    }

    /**
     * Setter for <code>li.t_meeting.meet_dev</code>.
     */
    public TMeeting setMeetDev(String meetDev) {
        this.meetDev = meetDev;
        return this;
    }

    /**
     * Getter for <code>li.t_meeting.meet_start</code>.
     */
    public LocalDateTime getMeetStart() {
        return this.meetStart;
    }

    /**
     * Setter for <code>li.t_meeting.meet_start</code>.
     */
    public TMeeting setMeetStart(LocalDateTime meetStart) {
        this.meetStart = meetStart;
        return this;
    }

    /**
     * Getter for <code>li.t_meeting.meet_end</code>.
     */
    public LocalDateTime getMeetEnd() {
        return this.meetEnd;
    }

    /**
     * Setter for <code>li.t_meeting.meet_end</code>.
     */
    public TMeeting setMeetEnd(LocalDateTime meetEnd) {
        this.meetEnd = meetEnd;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TMeeting (");

        sb.append(id);
        sb.append(", ").append(meetName);
        sb.append(", ").append(meetDue);
        sb.append(", ").append(meetroomName);
        sb.append(", ").append(meetDev);
        sb.append(", ").append(meetStart);
        sb.append(", ").append(meetEnd);

        sb.append(")");
        return sb.toString();
    }
}
