/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private String  userName;
    private String  userPassword;
    private Integer userAge;
    private Boolean userSex;
    private String  userPhone;
    private String  userEmail;
    private String  userRole;

    public TUser() {}

    public TUser(TUser value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.userPassword = value.userPassword;
        this.userAge = value.userAge;
        this.userSex = value.userSex;
        this.userPhone = value.userPhone;
        this.userEmail = value.userEmail;
        this.userRole = value.userRole;
    }

    public TUser(
        Integer userId,
        String  userName,
        String  userPassword,
        Integer userAge,
        Boolean userSex,
        String  userPhone,
        String  userEmail,
        String  userRole
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userAge = userAge;
        this.userSex = userSex;
        this.userPhone = userPhone;
        this.userEmail = userEmail;
        this.userRole = userRole;
    }

    /**
     * Getter for <code>li.t_user.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>li.t_user.user_id</code>.
     */
    public TUser setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>li.t_user.user_name</code>.
     */
    public TUser setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_password</code>.
     */
    public String getUserPassword() {
        return this.userPassword;
    }

    /**
     * Setter for <code>li.t_user.user_password</code>.
     */
    public TUser setUserPassword(String userPassword) {
        this.userPassword = userPassword;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_age</code>.
     */
    public Integer getUserAge() {
        return this.userAge;
    }

    /**
     * Setter for <code>li.t_user.user_age</code>.
     */
    public TUser setUserAge(Integer userAge) {
        this.userAge = userAge;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_sex</code>.
     */
    public Boolean getUserSex() {
        return this.userSex;
    }

    /**
     * Setter for <code>li.t_user.user_sex</code>.
     */
    public TUser setUserSex(Boolean userSex) {
        this.userSex = userSex;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_phone</code>.
     */
    public String getUserPhone() {
        return this.userPhone;
    }

    /**
     * Setter for <code>li.t_user.user_phone</code>.
     */
    public TUser setUserPhone(String userPhone) {
        this.userPhone = userPhone;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_email</code>.
     */
    public String getUserEmail() {
        return this.userEmail;
    }

    /**
     * Setter for <code>li.t_user.user_email</code>.
     */
    public TUser setUserEmail(String userEmail) {
        this.userEmail = userEmail;
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_role</code>.
     */
    public String getUserRole() {
        return this.userRole;
    }

    /**
     * Setter for <code>li.t_user.user_role</code>.
     */
    public TUser setUserRole(String userRole) {
        this.userRole = userRole;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userPassword);
        sb.append(", ").append(userAge);
        sb.append(", ").append(userSex);
        sb.append(", ").append(userPhone);
        sb.append(", ").append(userEmail);
        sb.append(", ").append(userRole);

        sb.append(")");
        return sb.toString();
    }
}
