/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserDev implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer userId;
    private Integer devId;

    public TUserDev() {}

    public TUserDev(TUserDev value) {
        this.id = value.id;
        this.userId = value.userId;
        this.devId = value.devId;
    }

    public TUserDev(
        Integer id,
        Integer userId,
        Integer devId
    ) {
        this.id = id;
        this.userId = userId;
        this.devId = devId;
    }

    /**
     * Getter for <code>li.t_user_dev.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>li.t_user_dev.id</code>.
     */
    public TUserDev setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>li.t_user_dev.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>li.t_user_dev.user_id</code>.
     */
    public TUserDev setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>li.t_user_dev.dev_id</code>.
     */
    public Integer getDevId() {
        return this.devId;
    }

    /**
     * Setter for <code>li.t_user_dev.dev_id</code>.
     */
    public TUserDev setDevId(Integer devId) {
        this.devId = devId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserDev (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(devId);

        sb.append(")");
        return sb.toString();
    }
}
