/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.records;


import com.example.demo.tables.TDepUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDepUserRecord extends UpdatableRecordImpl<TDepUserRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>li.t_dep_user.id</code>.
     */
    public TDepUserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>li.t_dep_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>li.t_dep_user.dep_id</code>.
     */
    public TDepUserRecord setDepId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>li.t_dep_user.dep_id</code>.
     */
    public Integer getDepId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>li.t_dep_user.user_id</code>.
     */
    public TDepUserRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>li.t_dep_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TDepUser.T_DEP_USER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TDepUser.T_DEP_USER.DEP_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TDepUser.T_DEP_USER.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getDepId();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getDepId();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public TDepUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TDepUserRecord value2(Integer value) {
        setDepId(value);
        return this;
    }

    @Override
    public TDepUserRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TDepUserRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDepUserRecord
     */
    public TDepUserRecord() {
        super(TDepUser.T_DEP_USER);
    }

    /**
     * Create a detached, initialised TDepUserRecord
     */
    public TDepUserRecord(Integer id, Integer depId, Integer userId) {
        super(TDepUser.T_DEP_USER);

        setId(id);
        setDepId(depId);
        setUserId(userId);
    }
}
