/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.records;


import com.example.demo.tables.TDevice;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDeviceRecord extends UpdatableRecordImpl<TDeviceRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>li.t_device.dev_id</code>.
     */
    public TDeviceRecord setDevId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>li.t_device.dev_id</code>.
     */
    public Integer getDevId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>li.t_device.dev_name</code>.
     */
    public TDeviceRecord setDevName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>li.t_device.dev_name</code>.
     */
    public String getDevName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TDevice.T_DEVICE.DEV_ID;
    }

    @Override
    public Field<String> field2() {
        return TDevice.T_DEVICE.DEV_NAME;
    }

    @Override
    public Integer component1() {
        return getDevId();
    }

    @Override
    public String component2() {
        return getDevName();
    }

    @Override
    public Integer value1() {
        return getDevId();
    }

    @Override
    public String value2() {
        return getDevName();
    }

    @Override
    public TDeviceRecord value1(Integer value) {
        setDevId(value);
        return this;
    }

    @Override
    public TDeviceRecord value2(String value) {
        setDevName(value);
        return this;
    }

    @Override
    public TDeviceRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDeviceRecord
     */
    public TDeviceRecord() {
        super(TDevice.T_DEVICE);
    }

    /**
     * Create a detached, initialised TDeviceRecord
     */
    public TDeviceRecord(Integer devId, String devName) {
        super(TDevice.T_DEVICE);

        setDevId(devId);
        setDevName(devName);
    }
}
