/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.records;


import com.example.demo.tables.TUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends UpdatableRecordImpl<TUserRecord> implements Record8<Integer, String, String, Integer, Boolean, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>li.t_user.user_id</code>.
     */
    public TUserRecord setUserId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>li.t_user.user_name</code>.
     */
    public TUserRecord setUserName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>li.t_user.user_password</code>.
     */
    public TUserRecord setUserPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_password</code>.
     */
    public String getUserPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>li.t_user.user_age</code>.
     */
    public TUserRecord setUserAge(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_age</code>.
     */
    public Integer getUserAge() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>li.t_user.user_sex</code>.
     */
    public TUserRecord setUserSex(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_sex</code>.
     */
    public Boolean getUserSex() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>li.t_user.user_phone</code>.
     */
    public TUserRecord setUserPhone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_phone</code>.
     */
    public String getUserPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>li.t_user.user_email</code>.
     */
    public TUserRecord setUserEmail(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_email</code>.
     */
    public String getUserEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>li.t_user.user_role</code>.
     */
    public TUserRecord setUserRole(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user.user_role</code>.
     */
    public String getUserRole() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Integer, Boolean, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, Integer, Boolean, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TUser.T_USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return TUser.T_USER.USER_NAME;
    }

    @Override
    public Field<String> field3() {
        return TUser.T_USER.USER_PASSWORD;
    }

    @Override
    public Field<Integer> field4() {
        return TUser.T_USER.USER_AGE;
    }

    @Override
    public Field<Boolean> field5() {
        return TUser.T_USER.USER_SEX;
    }

    @Override
    public Field<String> field6() {
        return TUser.T_USER.USER_PHONE;
    }

    @Override
    public Field<String> field7() {
        return TUser.T_USER.USER_EMAIL;
    }

    @Override
    public Field<String> field8() {
        return TUser.T_USER.USER_ROLE;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public String component3() {
        return getUserPassword();
    }

    @Override
    public Integer component4() {
        return getUserAge();
    }

    @Override
    public Boolean component5() {
        return getUserSex();
    }

    @Override
    public String component6() {
        return getUserPhone();
    }

    @Override
    public String component7() {
        return getUserEmail();
    }

    @Override
    public String component8() {
        return getUserRole();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public String value3() {
        return getUserPassword();
    }

    @Override
    public Integer value4() {
        return getUserAge();
    }

    @Override
    public Boolean value5() {
        return getUserSex();
    }

    @Override
    public String value6() {
        return getUserPhone();
    }

    @Override
    public String value7() {
        return getUserEmail();
    }

    @Override
    public String value8() {
        return getUserRole();
    }

    @Override
    public TUserRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public TUserRecord value3(String value) {
        setUserPassword(value);
        return this;
    }

    @Override
    public TUserRecord value4(Integer value) {
        setUserAge(value);
        return this;
    }

    @Override
    public TUserRecord value5(Boolean value) {
        setUserSex(value);
        return this;
    }

    @Override
    public TUserRecord value6(String value) {
        setUserPhone(value);
        return this;
    }

    @Override
    public TUserRecord value7(String value) {
        setUserEmail(value);
        return this;
    }

    @Override
    public TUserRecord value8(String value) {
        setUserRole(value);
        return this;
    }

    @Override
    public TUserRecord values(Integer value1, String value2, String value3, Integer value4, Boolean value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRecord
     */
    public TUserRecord() {
        super(TUser.T_USER);
    }

    /**
     * Create a detached, initialised TUserRecord
     */
    public TUserRecord(Integer userId, String userName, String userPassword, Integer userAge, Boolean userSex, String userPhone, String userEmail, String userRole) {
        super(TUser.T_USER);

        setUserId(userId);
        setUserName(userName);
        setUserPassword(userPassword);
        setUserAge(userAge);
        setUserSex(userSex);
        setUserPhone(userPhone);
        setUserEmail(userEmail);
        setUserRole(userRole);
    }
}
