/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.records;


import com.example.demo.tables.TUserDev;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserDevRecord extends UpdatableRecordImpl<TUserDevRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>li.t_user_dev.id</code>.
     */
    public TUserDevRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user_dev.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>li.t_user_dev.user_id</code>.
     */
    public TUserDevRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user_dev.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>li.t_user_dev.dev_id</code>.
     */
    public TUserDevRecord setDevId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>li.t_user_dev.dev_id</code>.
     */
    public Integer getDevId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TUserDev.T_USER_DEV.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TUserDev.T_USER_DEV.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TUserDev.T_USER_DEV.DEV_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getDevId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getDevId();
    }

    @Override
    public TUserDevRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TUserDevRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TUserDevRecord value3(Integer value) {
        setDevId(value);
        return this;
    }

    @Override
    public TUserDevRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserDevRecord
     */
    public TUserDevRecord() {
        super(TUserDev.T_USER_DEV);
    }

    /**
     * Create a detached, initialised TUserDevRecord
     */
    public TUserDevRecord(Integer id, Integer userId, Integer devId) {
        super(TUserDev.T_USER_DEV);

        setId(id);
        setUserId(userId);
        setDevId(devId);
    }
}
