/*
 * This file is generated by jOOQ.
 */
package com.example.demo;


import com.example.demo.tables.TDepUser;
import com.example.demo.tables.TDepment;
import com.example.demo.tables.TDevice;
import com.example.demo.tables.TMeeting;
import com.example.demo.tables.TMeetroom;
import com.example.demo.tables.TUser;
import com.example.demo.tables.TUserDev;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Li extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>li</code>
     */
    public static final Li LI = new Li();

    /**
     * The table <code>li.t_dep_user</code>.
     */
    public final TDepUser T_DEP_USER = TDepUser.T_DEP_USER;

    /**
     * The table <code>li.t_depment</code>.
     */
    public final TDepment T_DEPMENT = TDepment.T_DEPMENT;

    /**
     * The table <code>li.t_device</code>.
     */
    public final TDevice T_DEVICE = TDevice.T_DEVICE;

    /**
     * The table <code>li.t_meeting</code>.
     */
    public final TMeeting T_MEETING = TMeeting.T_MEETING;

    /**
     * The table <code>li.t_meetroom</code>.
     */
    public final TMeetroom T_MEETROOM = TMeetroom.T_MEETROOM;

    /**
     * The table <code>li.t_user</code>.
     */
    public final TUser T_USER = TUser.T_USER;

    /**
     * The table <code>li.t_user_dev</code>.
     */
    public final TUserDev T_USER_DEV = TUserDev.T_USER_DEV;

    /**
     * No further instances allowed
     */
    private Li() {
        super("li", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            TDepUser.T_DEP_USER,
            TDepment.T_DEPMENT,
            TDevice.T_DEVICE,
            TMeeting.T_MEETING,
            TMeetroom.T_MEETROOM,
            TUser.T_USER,
            TUserDev.T_USER_DEV);
    }
}
