/*
 * This file is generated by jOOQ.
 */
package com.example.demo;


import com.example.demo.tables.TDepUser;
import com.example.demo.tables.TDepment;
import com.example.demo.tables.TDevice;
import com.example.demo.tables.TMeeting;
import com.example.demo.tables.TMeetroom;
import com.example.demo.tables.TUser;
import com.example.demo.tables.TUserDev;


/**
 * Convenience access to all tables in li.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>li.t_dep_user</code>.
     */
    public static final TDepUser T_DEP_USER = TDepUser.T_DEP_USER;

    /**
     * The table <code>li.t_depment</code>.
     */
    public static final TDepment T_DEPMENT = TDepment.T_DEPMENT;

    /**
     * The table <code>li.t_device</code>.
     */
    public static final TDevice T_DEVICE = TDevice.T_DEVICE;

    /**
     * The table <code>li.t_meeting</code>.
     */
    public static final TMeeting T_MEETING = TMeeting.T_MEETING;

    /**
     * The table <code>li.t_meetroom</code>.
     */
    public static final TMeetroom T_MEETROOM = TMeetroom.T_MEETROOM;

    /**
     * The table <code>li.t_user</code>.
     */
    public static final TUser T_USER = TUser.T_USER;

    /**
     * The table <code>li.t_user_dev</code>.
     */
    public static final TUserDev T_USER_DEV = TUserDev.T_USER_DEV;
}
