/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.daos;


import com.example.demo.tables.TDevice;
import com.example.demo.tables.records.TDeviceRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TDeviceDao extends DAOImpl<TDeviceRecord, com.example.demo.tables.pojos.TDevice, Integer> {

    /**
     * Create a new TDeviceDao without any configuration
     */
    public TDeviceDao() {
        super(TDevice.T_DEVICE, com.example.demo.tables.pojos.TDevice.class);
    }

    /**
     * Create a new TDeviceDao with an attached configuration
     */
    @Autowired
    public TDeviceDao(Configuration configuration) {
        super(TDevice.T_DEVICE, com.example.demo.tables.pojos.TDevice.class, configuration);
    }

    @Override
    public Integer getId(com.example.demo.tables.pojos.TDevice object) {
        return object.getDevId();
    }

    /**
     * Fetch records that have <code>dev_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.tables.pojos.TDevice> fetchRangeOfDevId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TDevice.T_DEVICE.DEV_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dev_id IN (values)</code>
     */
    public List<com.example.demo.tables.pojos.TDevice> fetchByDevId(Integer... values) {
        return fetch(TDevice.T_DEVICE.DEV_ID, values);
    }

    /**
     * Fetch a unique record that has <code>dev_id = value</code>
     */
    public com.example.demo.tables.pojos.TDevice fetchOneByDevId(Integer value) {
        return fetchOne(TDevice.T_DEVICE.DEV_ID, value);
    }

    /**
     * Fetch records that have <code>dev_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.tables.pojos.TDevice> fetchRangeOfDevName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TDevice.T_DEVICE.DEV_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dev_name IN (values)</code>
     */
    public List<com.example.demo.tables.pojos.TDevice> fetchByDevName(String... values) {
        return fetch(TDevice.T_DEVICE.DEV_NAME, values);
    }
}
