/*
 * This file is generated by jOOQ.
 */
package com.example.demo.tables.daos;


import com.example.demo.tables.TUserDev;
import com.example.demo.tables.records.TUserDevRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TUserDevDao extends DAOImpl<TUserDevRecord, com.example.demo.tables.pojos.TUserDev, Integer> {

    /**
     * Create a new TUserDevDao without any configuration
     */
    public TUserDevDao() {
        super(TUserDev.T_USER_DEV, com.example.demo.tables.pojos.TUserDev.class);
    }

    /**
     * Create a new TUserDevDao with an attached configuration
     */
    @Autowired
    public TUserDevDao(Configuration configuration) {
        super(TUserDev.T_USER_DEV, com.example.demo.tables.pojos.TUserDev.class, configuration);
    }

    @Override
    public Integer getId(com.example.demo.tables.pojos.TUserDev object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.tables.pojos.TUserDev> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TUserDev.T_USER_DEV.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.demo.tables.pojos.TUserDev> fetchById(Integer... values) {
        return fetch(TUserDev.T_USER_DEV.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.demo.tables.pojos.TUserDev fetchOneById(Integer value) {
        return fetchOne(TUserDev.T_USER_DEV.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.tables.pojos.TUserDev> fetchRangeOfUserId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TUserDev.T_USER_DEV.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.demo.tables.pojos.TUserDev> fetchByUserId(Integer... values) {
        return fetch(TUserDev.T_USER_DEV.USER_ID, values);
    }

    /**
     * Fetch records that have <code>dev_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.demo.tables.pojos.TUserDev> fetchRangeOfDevId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TUserDev.T_USER_DEV.DEV_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dev_id IN (values)</code>
     */
    public List<com.example.demo.tables.pojos.TUserDev> fetchByDevId(Integer... values) {
        return fetch(TUserDev.T_USER_DEV.DEV_ID, values);
    }
}
