/*
 * This file is generated by jOOQ.
 */
package net.canway.demos.demo.pojos;


import java.io.Serializable;


/**
 * 部门信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  depName;
    private Integer depCount;

    public DepBean() {}

    public DepBean(DepBean value) {
        this.id = value.id;
        this.depName = value.depName;
        this.depCount = value.depCount;
    }

    public DepBean(
        Integer id,
        String  depName,
        Integer depCount
    ) {
        this.id = id;
        this.depName = depName;
        this.depCount = depCount;
    }

    /**
     * Getter for <code>shunwenbaby.t_dep.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>shunwenbaby.t_dep.ID</code>.
     */
    public DepBean setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_dep.DEP_NAME</code>. 部门名称
     */
    public String getDepName() {
        return this.depName;
    }

    /**
     * Setter for <code>shunwenbaby.t_dep.DEP_NAME</code>. 部门名称
     */
    public DepBean setDepName(String depName) {
        this.depName = depName;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_dep.DEP_COUNT</code>. 部门人数
     */
    public Integer getDepCount() {
        return this.depCount;
    }

    /**
     * Setter for <code>shunwenbaby.t_dep.DEP_COUNT</code>. 部门人数
     */
    public DepBean setDepCount(Integer depCount) {
        this.depCount = depCount;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDep (");

        sb.append(id);
        sb.append(", ").append(depName);
        sb.append(", ").append(depCount);

        sb.append(")");
        return sb.toString();
    }
}
