/*
 * This file is generated by jOOQ.
 */
package net.canway.demos.demo.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeetroomBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  roomName;
    private Integer rootSize;
    private Boolean roomState;

    public MeetroomBean() {}

    public MeetroomBean(MeetroomBean value) {
        this.id = value.id;
        this.roomName = value.roomName;
        this.rootSize = value.rootSize;
        this.roomState = value.roomState;
    }

    public MeetroomBean(
        Integer id,
        String  roomName,
        Integer rootSize,
        Boolean roomState
    ) {
        this.id = id;
        this.roomName = roomName;
        this.rootSize = rootSize;
        this.roomState = roomState;
    }

    /**
     * Getter for <code>li.t_meetroom.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>li.t_meetroom.id</code>.
     */
    public MeetroomBean setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>li.t_meetroom.room_name</code>.
     */
    public String getRoomName() {
        return this.roomName;
    }

    /**
     * Setter for <code>li.t_meetroom.room_name</code>.
     */
    public MeetroomBean setRoomName(String roomName) {
        this.roomName = roomName;
        return this;
    }

    /**
     * Getter for <code>li.t_meetroom.root_size</code>.
     */
    public Integer getRootSize() {
        return this.rootSize;
    }

    /**
     * Setter for <code>li.t_meetroom.root_size</code>.
     */
    public MeetroomBean setRootSize(Integer rootSize) {
        this.rootSize = rootSize;
        return this;
    }

    /**
     * Getter for <code>li.t_meetroom.room_state</code>.
     */
    public Boolean getRoomState() {
        return this.roomState;
    }

    /**
     * Setter for <code>li.t_meetroom.room_state</code>.
     */
    public MeetroomBean setRoomState(Boolean roomState) {
        this.roomState = roomState;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TMeetroom (");

        sb.append(id);
        sb.append(", ").append(roomName);
        sb.append(", ").append(rootSize);
        sb.append(", ").append(roomState);

        sb.append(")");
        return sb.toString();
    }
}
