/*
 * This file is generated by jOOQ.
 */
package net.canway.demos.demo.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  sbName;

    public SbBean() {}

    public SbBean(SbBean value) {
        this.id = value.id;
        this.sbName = value.sbName;
    }

    public SbBean(
        Integer id,
        String  sbName
    ) {
        this.id = id;
        this.sbName = sbName;
    }

    /**
     * Getter for <code>shunwenbaby.t_sb.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>shunwenbaby.t_sb.ID</code>.
     */
    public SbBean setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_sb.SB_NAME</code>.
     */
    public String getSbName() {
        return this.sbName;
    }

    /**
     * Setter for <code>shunwenbaby.t_sb.SB_NAME</code>.
     */
    public SbBean setSbName(String sbName) {
        this.sbName = sbName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TSb (");

        sb.append(id);
        sb.append(", ").append(sbName);

        sb.append(")");
        return sb.toString();
    }
}
