/*
 * This file is generated by jOOQ.
 */
package net.canway.demos.demo.pojos;


import java.io.Serializable;


/**
 * 用户信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String userName;
    private String  password;
    private Integer age;
    private Boolean sex;
    private String  phone;
    private String  email;
    private String  role;


    public UserBean() {}

    public UserBean(UserBean value) {
        this.id = value.id;
        this.userName = value.userName;
        this.password = value.password;
        this.age = value.age;
        this.sex = value.sex;
        this.phone = value.phone;
        this.email = value.email;
        this.role = value.role;

    }

    public UserBean(
        Integer id,
        String userName,
        String  password,
        Integer age,
        Boolean sex,
        String  phone,
        String  email,
        String  role

    ) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.age = age;
        this.sex = sex;
        this.phone = phone;
        this.email = email;
        this.role = role;

    }

    /**
     * Getter for <code>shunwenbaby.t_user.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.ID</code>.
     */
    public UserBean setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.USER_NAME</code>. 用户名称
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.USER_NAME</code>. 用户名称
     */
    public UserBean setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.PASSWORD</code>. 密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.PASSWORD</code>. 密码
     */
    public UserBean setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.AGE</code>. 年龄
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.AGE</code>. 年龄
     */
    public UserBean setAge(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.SEX</code>. 性别
     */
    public Boolean getSex() {
        return this.sex;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.SEX</code>. 性别
     */
    public UserBean setSex(Boolean sex) {
        this.sex = sex;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.PHONE</code>. 手机号码
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.PHONE</code>. 手机号码
     */
    public UserBean setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.EMAIL</code>. 邮箱
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.EMAIL</code>. 邮箱
     */
    public UserBean setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.ROLE</code>. 角色
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>shunwenbaby.t_user.ROLE</code>. 角色
     */
    public UserBean setRole(String role) {
        this.role = role;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user.DEP_ID</code>. 部门ID
     */

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(age);
        sb.append(", ").append(sex);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(role);


        sb.append(")");
        return sb.toString();
    }
}
