/*
 * This file is generated by jOOQ.
 */
package net.canway.demos.demo.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSbBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer sbId;
    private String  sbName;
    private Integer userId;

    public UserSbBean() {}

    public UserSbBean(UserSbBean value) {
        this.sbId = value.sbId;
        this.sbName = value.sbName;
        this.userId = value.userId;
    }

    public UserSbBean(
        Integer sbId,
        String  sbName,
        Integer userId
    ) {
        this.sbId = sbId;
        this.sbName = sbName;
        this.userId = userId;
    }

    /**
     * Getter for <code>shunwenbaby.t_user_sb.SB_ID</code>.
     */
    public Integer getSbId() {
        return this.sbId;
    }

    /**
     * Setter for <code>shunwenbaby.t_user_sb.SB_ID</code>.
     */
    public UserSbBean setSbId(Integer sbId) {
        this.sbId = sbId;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user_sb.SB_NAME</code>.
     */
    public String getSbName() {
        return this.sbName;
    }

    /**
     * Setter for <code>shunwenbaby.t_user_sb.SB_NAME</code>.
     */
    public UserSbBean setSbName(String sbName) {
        this.sbName = sbName;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user_sb.USER_ID</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>shunwenbaby.t_user_sb.USER_ID</code>.
     */
    public UserSbBean setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserSb (");

        sb.append(sbId);
        sb.append(", ").append(sbName);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
