/*
 * This file is generated by jOOQ.
 */
package net.canway.demos.demo.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDepBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer userId;
    private Integer depId;

    public UserDepBean() {}

    public UserDepBean(UserDepBean value) {
        this.id = value.id;
        this.userId = value.userId;
        this.depId = value.depId;
    }

    public UserDepBean(
        Integer id,
        Integer userId,
        Integer depId
    ) {
        this.id = id;
        this.userId = userId;
        this.depId = depId;
    }

    /**
     * Getter for <code>shunwenbaby.t_user_dep.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>shunwenbaby.t_user_dep.ID</code>.
     */
    public UserDepBean setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user_dep.USER_ID</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>shunwenbaby.t_user_dep.USER_ID</code>.
     */
    public UserDepBean setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>shunwenbaby.t_user_dep.DEP_ID</code>.
     */
    public Integer getDepId() {
        return this.depId;
    }

    /**
     * Setter for <code>shunwenbaby.t_user_dep.DEP_ID</code>.
     */
    public UserDepBean setDepId(Integer depId) {
        this.depId = depId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserDep (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(depId);

        sb.append(")");
        return sb.toString();
    }
}
